### ISSUE TITLE
Creating RCM roadmap and project board

### ISSUE THREAD

**Issue by EKaroune** [alan-turing-institute/open-community-building#217]
### Summary Sentence

We need to plan a roadmap with milestones and issues that can be made into an actionable project board. 

### What needs to be done?

- [ ] Take the notes from the RCM team day
- [ ] Decide milestones
- [ ] Sort tasks under the milestones
- [ ] Create milestones and sort issues in a project board.

### Who can help?

All RCMs.
---

### Update after the issue was opened

[Add details]
